import "server-only";

import { createAdminClient } from "@/lib/supabase/admin";
import { ResendRequestError, ResendUnknownOutcomeError, sendResendEmail } from "@/lib/resend/server";
const escape=(value:string)=>value.replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]!);
export async function dispatchLessonProposalEmail(proposalId:string){
 const admin=createAdminClient(); const {data:delivery,error}=await admin.from("lesson_proposal_email_outbox").select("id,recipient_email,subject,message_text,idempotency_key").eq("proposal_id",proposalId).eq("status","pending").maybeSingle();
 if(error||!delivery)return;
 try{const sent=await sendResendEmail({from:"Common Time <notifications@notifications.commontime.studio>",to:delivery.recipient_email,subject:delivery.subject,text:delivery.message_text,html:`<div style="font-family:Arial,sans-serif;line-height:1.65"><h1>${escape(delivery.subject)}</h1><p>${escape(delivery.message_text)}</p></div>`,idempotencyKey:delivery.idempotency_key,messageKind:"lesson_schedule_proposal",timeoutMs:10_000}); const recorded=await admin.from("lesson_proposal_email_outbox").update({status:"accepted",provider_email_id:sent.id,accepted_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",delivery.id).eq("status","pending"); if(recorded.error)console.error("Proposal email accepted but finalization failed",{proposalId,code:recorded.error.code});}
 catch(caught){if(caught instanceof ResendUnknownOutcomeError){const marked=await admin.from("lesson_proposal_email_outbox").update({status:"reconciliation_required",provider_error_code:"provider_outcome_unknown",provider_error_message:caught.message.slice(0,500),updated_at:new Date().toISOString()}).eq("id",delivery.id).eq("status","pending");if(marked.error)console.error("Proposal email unknown outcome could not be recorded",{proposalId,code:marked.error.code});return;}const provider=caught instanceof ResendRequestError?caught:null; const recorded=await admin.from("lesson_proposal_email_outbox").update({status:"failed",provider_error_code:provider?.code??"request_failed",provider_error_message:caught instanceof Error?caught.message.slice(0,500):"Provider request failed",failed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",delivery.id).eq("status","pending"); if(recorded.error)console.error("Proposal email failure could not be recorded",{proposalId,code:recorded.error.code});}
}
