"use client";
import { useState, useTransition } from "react";
import { previewLessonRequest, submitLessonRequest } from "@/app/portal/lesson-request-actions";
import { HoldToConfirm } from "@/components/ui/hold-to-confirm";
type Kind="cancellation"|"reschedule";
type Preview=Awaited<ReturnType<typeof previewLessonRequest>> extends infer R?R extends {ok:true;preview:infer P}?P:never:never;
export function LessonRequestControls({lessonId,timeZone}:{lessonId:string;timeZone:string}){
 const [pending,startTransition]=useTransition(),[kind,setKind]=useState<Kind|null>(null),[preview,setPreview]=useState<Preview|null>(null),[receipt,setReceipt]=useState<{at:string;emailFailed:boolean}|null>(null),[message,setMessage]=useState("");
 function prepare(next:Kind){startTransition(async()=>{setMessage("");const result=await previewLessonRequest(lessonId,next);if(!result.ok)return setMessage(result.message);setKind(next);setPreview(result.preview);});}
 async function submit(){if(!kind||!preview)return{ok:false,message:"Prepare the request first."};const accounted=!["unaccounted","draft"].includes(preview.accounting_state),resolution=kind==="reschedule"?"reschedule":accounted?"lesson_credit":"cancel",result=await submitLessonRequest(lessonId,kind,resolution);if(!result.ok)return result;setReceipt({at:result.requestedAt,emailFailed:result.deliveryFailed});setPreview(null);return{ok:true,message:"Request recorded."};}
 if(receipt)return <section className="mt-8 border-l-2 border-brand pl-5"><h3 className="font-display text-2xl">Request sent</h3><p className="mt-3 text-sm leading-6">Recorded {new Intl.DateTimeFormat("en-US",{timeZone,dateStyle:"long",timeStyle:"short"}).format(new Date(receipt.at))}.</p><p className="mt-2 text-sm leading-6 text-muted">This recorded time determines how the policy applies. The lesson remains scheduled until the school confirms a change.</p>{receipt.emailFailed?<p className="mt-3 text-xs text-danger">Your request was recorded, but at least one confirmation email could not be submitted. The school notification remains in the app.</p>:<p className="mt-3 text-xs text-muted">A receipt was emailed to you, and the school was notified.</p>}</section>;
 return <section className="mt-8 border-t border-line pt-6"><h3 className="font-display text-2xl">Change this lesson</h3>{!preview?<div className="mt-5 grid gap-3"><button disabled={pending} onClick={()=>prepare("cancellation")} className="border border-line px-4 py-3 text-left text-sm hover:border-brand disabled:opacity-50">Request cancellation</button><button disabled={pending} onClick={()=>prepare("reschedule")} className="border border-line px-4 py-3 text-left text-sm hover:border-brand disabled:opacity-50">Request reschedule</button></div>:<div className="mt-5 border-l-2 border-brand pl-5"><p className="text-sm font-medium">{preview.within_policy_window?"This request is within the policy window.":"This request is outside the policy window."}</p><p className="mt-3 text-sm leading-6 text-muted">The school requires {preview.cutoff_hours} hours’ notice. {preview.policy_guidance}</p>{!preview.within_policy_window&&preview.policy_disposition==="charge"?<p className="mt-3 text-sm leading-6 text-danger">If canceled, this lesson will still be counted as a serviced lesson.</p>:null}<p className="mt-3 text-sm leading-6 text-muted">Your submission time will be recorded and remains authoritative even if the school responds later. The lesson stays scheduled until the school confirms the change.</p><div className="mt-5"><HoldToConfirm action={submit} idleLabel={`Hold to send ${kind} request`} holdingLabel="Keep holding to send…" submittingLabel="Sending request…" successLabel="Request sent"/><button disabled={pending} onClick={()=>{setPreview(null);setKind(null);}} className="mt-2 w-full px-4 py-3 text-sm text-muted">Back</button></div></div>}{message?<p role="status" className="mt-4 text-sm text-danger">{message}</p>:null}</section>;
}
