"use client";

import { useActionState } from "react";
import { MdErrorOutline, MdExpandMore } from "react-icons/md";
import { rejectBillingRequest, type RejectBillingState } from "./actions";

const initialState: RejectBillingState = { ok: false, message: "" };

export function RejectChargesForm({ token }: { token: string }) {
  const [state, action, pending] = useActionState(rejectBillingRequest.bind(null, token), initialState);
  return <details className="ui-card group mt-6 p-6 sm:p-7"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 marker:hidden"><span className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-danger/10 text-xl text-danger"><MdErrorOutline aria-hidden="true" /></span><span><span className="block text-xs uppercase tracking-[0.14em] text-danger">Something needs correcting</span><span className="mt-1 block font-display text-2xl text-ink">Send these charges back for review</span><span className="mt-1 block text-sm leading-6 text-muted">Tell the school what looks wrong. Nothing will be charged.</span></span></span><MdExpandMore aria-hidden="true" className="shrink-0 text-2xl text-muted transition group-open:rotate-180" /></summary><form action={action} className="mt-6 grid gap-5 border-t border-line pt-6"><label><span className="block text-xs text-muted">What needs review?</span><select name="reason" required defaultValue="" className="mt-2 w-full border-b border-line bg-transparent py-2 outline-none focus:border-brand"><option value="" disabled>Select a reason</option><option value="lesson_did_not_happen">A lesson did not happen</option><option value="wrong_lesson_or_date">A lesson or date is wrong</option><option value="wrong_amount">An amount is wrong</option><option value="missing_credit">A credit or discount is missing</option><option value="duplicate_charge">A charge appears twice</option><option value="other">Other</option></select></label><label><span className="block text-xs text-muted">Note to the school · optional unless Other</span><textarea name="note" maxLength={1000} rows={4} placeholder="For example: We did not have the August 4 lesson." className="mt-2 w-full resize-y rounded-card border border-line bg-transparent p-3 outline-none focus:border-brand" /></label><div className="flex flex-wrap items-center justify-between gap-4"><p className="max-w-lg text-xs leading-5 text-muted">This stops the current proposal and returns it to the school. It does not change the statement by itself.</p><button disabled={pending} className="border border-danger/60 px-5 py-3 text-sm text-danger transition hover:bg-danger hover:text-canvas disabled:opacity-50">{pending ? "Sending…" : "Send back for review"}</button></div>{state.message ? <p role="status" className={`text-sm ${state.ok ? "text-muted" : "text-danger"}`}>{state.message}</p> : null}</form></details>;
}
