import Link from "next/link";
import { notFound,redirect } from "next/navigation";
import { ApprovalList } from "@/components/approvals/approval-list";
import { loadOwnerApprovals } from "@/lib/approvals/owner-approvals";
import { createClient } from "@/lib/supabase/server";
import { ProposalReview } from "../notifications/proposal-review";
export const dynamic="force-dynamic";
export default async function ApprovalsPage({params,searchParams}:{params:Promise<{schoolId:string}>;searchParams:Promise<{proposal?:string;view?:string}>}){
 const {schoolId}=await params,{proposal:proposalId,view}=await searchParams,supabase=await createClient(),{data:auth}=await supabase.auth.getClaims(),profileId=auth?.claims?.sub;if(!profileId)redirect(`/login?next=/schools/${schoolId}/approvals`);
 const [{data:school},{data:membership}]=await Promise.all([supabase.from("schools").select("name,timezone").eq("id",schoolId).maybeSingle(),supabase.from("school_members").select("role").eq("school_id",schoolId).eq("profile_id",profileId).eq("status","active").maybeSingle()]);if(!school||!membership||!["owner","admin"].includes(membership.role))notFound();
 const history=view==="history",items=await loadOwnerApprovals(supabase,schoolId,{history}),selected=proposalId?[...items,...await loadOwnerApprovals(supabase,schoolId,{history:!history})].find(item=>item.id===proposalId):null;
 const format=new Intl.DateTimeFormat("en-US",{timeZone:school.timezone,weekday:"long",month:"long",day:"numeric",hour:"numeric",minute:"2-digit"});
 return <main className="mx-auto min-h-screen max-w-5xl px-5 py-10 sm:px-8 sm:py-section"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-line pb-7"><div><p className="text-sm text-brand">{school.name}</p><h1 className="mt-3 font-display text-5xl">Approvals</h1><p className="mt-3 text-sm text-muted">Durable requests that need an owner decision.</p></div><nav className="flex gap-5 text-sm"><Link href={`/schools/${schoolId}/approvals`} className={!history?"text-brand":"text-muted"}>Pending</Link><Link href={`/schools/${schoolId}/approvals?view=history`} className={history?"text-brand":"text-muted"}>History</Link></nav></header><div className="mt-8"><ApprovalList schoolId={schoolId} items={items} timezone={school.timezone}/></div>{selected?<ProposalReview schoolId={schoolId} proposalId={selected.id} status={selected.status} student={selected.student} teacher={selected.teacher} original={selected.original?format.format(new Date(selected.original)):"Original time unavailable"} proposed={format.format(new Date(selected.proposed))} reason={selected.reason} closeHref={`/schools/${schoolId}/approvals${history?"?view=history":""}`}/>:proposalId?<p className="mt-8 text-sm text-danger">That approval is unavailable.</p>:null}</main>;
}
