"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect,useMemo,useState } from "react";
import { resolveLessonChangeRequest } from "@/app/schools/[schoolId]/approvals/actions";
import type { LessonRequestApproval } from "@/lib/approvals/owner-approvals";
import { HoldToConfirm } from "@/components/ui/hold-to-confirm";

const labels:Record<string,string>={count_as_serviced:"Count as serviced; no replacement",retain_for_reschedule:"Place in Lessons to Schedule",waive:"Cancel without counting it as serviced",manual_review:"Owner decides each request"};

export function LessonRequestReview({schoolId,item,timezone,closeHref}:{schoolId:string;item:LessonRequestApproval;timezone:string;closeHref:string}){
 const router=useRouter(),pending=["pending","in_progress"].includes(item.status),defaultResolution=item.policyLessonResolution==="manual_review"?"retain_for_reschedule":item.policyLessonResolution;
 const [resolution,setResolution]=useState(defaultResolution),[adjustmentKind,setAdjustmentKind]=useState<"none"|"fee"|"credit">(item.policyFeeCents>0?"fee":"none"),[amount,setAmount]=useState(item.policyFeeCents/100),[reason,setReason]=useState("");
 const format=useMemo(()=>new Intl.DateTimeFormat("en-US",{timeZone:timezone,weekday:"long",month:"long",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"}),[timezone]);
 const money=useMemo(()=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}),[]),amountCents=Math.round(Number.isFinite(amount)?amount*100:0),isOverride=resolution!==item.policyLessonResolution||amountCents!==item.policyFeeCents||(item.policyFeeCents>0?adjustmentKind!=="fee":adjustmentKind!=="none");
 const requestName=item.requestType==="reschedule"?"Reschedule request":"Cancellation request";
 const requestedAction=item.requestedResolution==="reschedule"?"Keep this lesson available for another time":item.requestedResolution==="lesson_credit"?"Cancel and apply the value to the family account":"Cancel this lesson";
 useEffect(()=>{const previous=document.body.style.overflow;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")router.push(closeHref);};document.body.style.overflow="hidden";window.addEventListener("keydown",close);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",close);};},[router,closeHref]);
 async function submit(decision:"approved"|"declined"){const result=await resolveLessonChangeRequest(schoolId,item.id,{decision,lessonResolution:decision==="approved"?resolution:null,adjustmentKind:decision==="approved"&&adjustmentKind!=="none"?adjustmentKind:null,adjustmentAmountCents:decision==="approved"?amountCents:0,reason});if(result.ok){window.dispatchEvent(new CustomEvent("common-time:toast",{detail:{title:"Request resolved",message:result.message}}));router.push(closeHref);router.refresh();}return result;}
 const summary=resolution==="count_as_serviced"?`Cancel the scheduled lesson and count it as serviced.`:resolution==="retain_for_reschedule"?`Cancel the scheduled lesson and place one lesson in ${item.student}’s Lessons to Schedule pool.`:`Cancel the scheduled lesson without counting it as serviced.`;
 return <div className="fixed inset-0 z-[100]" role="dialog" aria-modal="true" aria-labelledby="lesson-request-title"><Link href={closeHref} aria-label="Close request review" className="fixed inset-0 bg-[var(--ui-overlay)]"/><section className="fixed left-1/2 top-1/2 z-[101] max-h-[calc(100dvh-2rem)] w-[min(48rem,calc(100%-2rem))] -translate-x-1/2 -translate-y-1/2 overflow-y-auto border border-brand bg-canvas p-5 shadow-xl sm:p-8"><div className="flex items-start justify-between gap-5"><div><p className="text-xs uppercase tracking-[0.14em] text-brand">{requestName}</p><h2 id="lesson-request-title" className="mt-3 font-display text-4xl">{requestName} for {item.student}.</h2><p className="mt-3 text-sm leading-6 text-muted">Family requested: {requestedAction}.</p></div><Link href={closeHref} className="text-sm text-muted hover:text-ink">Close</Link></div>
 <dl className="mt-7 grid gap-px bg-line sm:grid-cols-2"><div className="bg-canvas p-5"><dt className="text-xs text-muted">Student</dt><dd className="mt-2 text-sm font-medium">{item.student}</dd></div><div className="bg-canvas p-5"><dt className="text-xs text-muted">Teacher</dt><dd className="mt-2 text-sm font-medium">{item.teacher}</dd></div><div className="bg-canvas p-5"><dt className="text-xs text-muted">Lesson</dt><dd className="mt-2 text-sm">{format.format(new Date(item.lessonAt))}</dd></div><div className="bg-canvas p-5"><dt className="text-xs text-muted">Request recorded</dt><dd className="mt-2 text-sm">{format.format(new Date(item.requestedAt))}</dd></div></dl>
 <section className="mt-6 border-l-2 border-brand pl-5"><p className="text-sm font-medium">{item.withinPolicyWindow?"Within":"Outside"} the {item.cutoffHours}-hour policy window</p><p className="mt-2 text-sm leading-6 text-muted">{item.policyGuidance}</p><p className="mt-3 text-sm"><span className="text-muted">Policy recommendation: </span>{labels[item.policyLessonResolution]??item.policyLessonResolution}{item.policyFeeCents>0?` with a ${money.format(item.policyFeeCents/100)} fee`:""}.</p></section>
 {pending?<><div className="mt-8 space-y-6"><label className="block"><span className="text-sm font-medium">What happens to the lesson?</span><select value={resolution} onChange={event=>setResolution(event.target.value)} className="mt-2 w-full border-b border-line bg-transparent py-3 outline-none focus:border-brand"><option value="count_as_serviced">Count as serviced; no replacement</option><option value="retain_for_reschedule">Place in Lessons to Schedule</option><option value="waive">Cancel without counting it as serviced</option></select></label><div className="grid gap-5 sm:grid-cols-2"><label><span className="text-sm font-medium">Financial adjustment</span><select value={adjustmentKind} onChange={event=>setAdjustmentKind(event.target.value as typeof adjustmentKind)} className="mt-2 w-full border-b border-line bg-transparent py-3"><option value="none">No additional adjustment</option><option value="fee">Add a fee</option><option value="credit">Add a credit</option></select></label>{adjustmentKind!=="none"?<label><span className="text-sm font-medium">Amount</span><div className="relative"><span className="absolute left-0 top-5 text-muted">$</span><input type="number" min="0.01" max="10000" step="0.01" value={amount} onChange={event=>setAmount(Number(event.target.value))} className="mt-2 w-full border-b border-line bg-transparent py-3 pl-5"/></div></label>:null}</div><label className="block"><span className="text-sm font-medium">Internal decision note {isOverride?"· required for this exception":"· optional"}</span><textarea value={reason} onChange={event=>setReason(event.target.value)} maxLength={1000} rows={3} className="mt-2 w-full border border-line bg-transparent p-3 outline-none focus:border-brand" placeholder="What did you agree on with the family?"/></label></div>
 <aside className="mt-7 bg-surface-raised p-5"><p className="text-xs uppercase tracking-[0.12em] text-brand">Before you confirm</p><p className="mt-3 text-sm leading-6">{summary}{adjustmentKind!=="none"&&amountCents>0?` Record a ${money.format(amountCents/100)} ${adjustmentKind}.`:""}</p>{isOverride?<p className="mt-2 text-xs text-muted">This differs from the published policy and will be recorded as an owner exception.</p>:null}</aside>
 <div className="mt-7 grid gap-4 sm:grid-cols-2"><HoldToConfirm action={()=>submit("approved")} disabled={isOverride&&!reason.trim()||adjustmentKind!=="none"&&amountCents<=0} idleLabel="Hold to apply this decision" holdingLabel="Keep holding to resolve…" submittingLabel="Applying lesson and account changes…" successLabel="Request resolved"/><HoldToConfirm action={()=>submit("declined")} idleLabel="Hold to decline and leave scheduled" holdingLabel="Keep holding to decline…" submittingLabel="Declining request…" successLabel="Request declined"/></div></>:<p className="mt-7 text-sm capitalize text-muted">This request is {item.status.replaceAll("_"," ")}.</p>}
 </section></div>;
}
