import type { createClient } from "@/lib/supabase/server";

type Client = Awaited<ReturnType<typeof createClient>>;
type ProposalApproval = { kind:"schedule_proposal";id:string;status:string;teacherId:string;studentId:string;teacher:string;student:string;original:string|null;proposed:string;reason:string;createdAt:string };
export type LessonRequestApproval = { kind:"lesson_change_request";id:string;status:string;teacherId:string;studentId:string;teacher:string;student:string;lessonAt:string;lessonEndsAt:string;requestType:string;originKind:string;scenario:string;requestedResolution:string;requestedAt:string;withinPolicyWindow:boolean;cutoffHours:number;policyGuidance:string;accountingState:string;policyLessonResolution:string;policyFeeCents:number;replacementWindowDays:number|null };
export type OwnerApprovalItem = ProposalApproval | LessonRequestApproval;

export async function loadOwnerApprovals(client:Client,schoolId:string,{teacherId,studentIds,history=false}:{teacherId?:string;studentIds?:string[];history?:boolean}={}){
 let proposalQuery=client.from("lesson_schedule_proposals").select("id,status,teacher_id,student_id,original_starts_at,proposed_starts_at,reason,created_at").eq("school_id",schoolId).eq("proposal_kind","reschedule").order("created_at",{ascending:false});
 proposalQuery=history?proposalQuery.neq("status","pending_owner"):proposalQuery.eq("status","pending_owner");
 if(teacherId)proposalQuery=proposalQuery.eq("teacher_id",teacherId);if(studentIds)proposalQuery=studentIds.length?proposalQuery.in("student_id",studentIds):proposalQuery.in("student_id",["00000000-0000-0000-0000-000000000000"]);
 let requestQuery=client.from("lesson_change_requests").select("id,status,lesson_event_id,request_type,origin_kind,scenario,requested_resolution,requested_at,within_policy_window,cutoff_hours,policy_guidance,accounting_state,policy_version_id").eq("school_id",schoolId).order("requested_at",{ascending:false});
 requestQuery=history?requestQuery.in("status",["approved","declined","withdrawn","superseded"]):requestQuery.in("status",["pending","in_progress"]);
 const [{data:proposalRows,error:proposalError},{data:requestRows,error:requestError}]=await Promise.all([proposalQuery,requestQuery]);
 if(proposalError)throw new Error(`Approvals could not load: ${proposalError.message}`);if(requestError)throw new Error(`Lesson requests could not load: ${requestError.message}`);
 const eventIds=(requestRows??[]).map(row=>row.lesson_event_id);const {data:events,error:eventError}=eventIds.length?await client.from("lesson_events").select("id,student_id,teacher_id,starts_at,ends_at").eq("school_id",schoolId).in("id",eventIds):{data:[],error:null};if(eventError)throw new Error(`Request lessons could not load: ${eventError.message}`);
 const eventMap=new Map((events??[]).map(event=>[event.id,event]));
 const filteredRequests=(requestRows??[]).filter(row=>{const event=eventMap.get(row.lesson_event_id);return event&&(!teacherId||event.teacher_id===teacherId)&&(!studentIds||studentIds.includes(event.student_id));});
 const ids=[...new Set([...(proposalRows??[]).flatMap(row=>[row.teacher_id,row.student_id]),...filteredRequests.flatMap(row=>{const event=eventMap.get(row.lesson_event_id);return event?[event.teacher_id,event.student_id]:[];})])];
 const versionIds=[...new Set(filteredRequests.map(row=>row.policy_version_id))];
 const [{data:people,error:peopleError},{data:rules,error:rulesError}]=await Promise.all([ids.length?client.from("people").select("id,first_name,last_name,preferred_name").eq("school_id",schoolId).in("id",ids):Promise.resolve({data:[],error:null}),versionIds.length?client.from("cancellation_policy_rules").select("policy_version_id,late_lesson_resolution,late_reschedule_fee_cents,replacement_window_days,timely_cancel_disposition").in("policy_version_id",versionIds):Promise.resolve({data:[],error:null})]);
 if(peopleError)throw new Error(`Approval people could not load: ${peopleError.message}`);if(rulesError)throw new Error(`Approval policies could not load: ${rulesError.message}`);
 const names=new Map((people??[]).map(person=>[person.id,`${person.preferred_name||person.first_name} ${person.last_name}`]));const ruleMap=new Map((rules??[]).map(rule=>[rule.policy_version_id,rule]));
 const proposals:ProposalApproval[]=(proposalRows??[]).map(row=>({kind:"schedule_proposal",id:row.id,status:row.status,teacherId:row.teacher_id,studentId:row.student_id,teacher:names.get(row.teacher_id)??"Teacher",student:names.get(row.student_id)??"Student",original:row.original_starts_at,proposed:row.proposed_starts_at,reason:row.reason,createdAt:row.created_at}));
 const requests:LessonRequestApproval[]=filteredRequests.flatMap(row=>{const event=eventMap.get(row.lesson_event_id),rule=ruleMap.get(row.policy_version_id);if(!event||!rule)return[];const timely=rule.timely_cancel_disposition;const timelyResolution=timely==="charge"?"count_as_serviced":timely==="manual_review"?"manual_review":row.requested_resolution==="reschedule"||timely==="credit"?"retain_for_reschedule":"waive";return[{kind:"lesson_change_request",id:row.id,status:row.status,teacherId:event.teacher_id,studentId:event.student_id,teacher:names.get(event.teacher_id)??"Teacher",student:names.get(event.student_id)??"Student",lessonAt:event.starts_at,lessonEndsAt:event.ends_at,requestType:row.request_type,originKind:row.origin_kind,scenario:row.scenario,requestedResolution:row.requested_resolution,requestedAt:row.requested_at,withinPolicyWindow:row.within_policy_window,cutoffHours:row.cutoff_hours,policyGuidance:row.policy_guidance,accountingState:row.accounting_state,policyLessonResolution:row.within_policy_window?timelyResolution:rule.late_lesson_resolution,policyFeeCents:row.within_policy_window?0:rule.late_reschedule_fee_cents,replacementWindowDays:rule.replacement_window_days}];});
 return [...proposals,...requests].sort((a,b)=>new Date(b.kind==="schedule_proposal"?b.createdAt:b.requestedAt).getTime()-new Date(a.kind==="schedule_proposal"?a.createdAt:a.requestedAt).getTime()) satisfies OwnerApprovalItem[];
}
