import type { createClient } from "@/lib/supabase/server";

type Client = Awaited<ReturnType<typeof createClient>>;
type ProposalApproval = { kind:"schedule_proposal";id:string;status:string;teacherId:string;studentId:string;teacher:string;student:string;original:string|null;proposed:string;reason:string;createdAt:string };
export type LessonRequestApproval = { kind:"lesson_change_request";id:string;status:string;teacherId:string;studentId:string;teacher:string;student:string;lessonAt:string;lessonEndsAt:string;requestType:string;originKind:string;scenario:string;requestedResolution:string;requestedAt:string;withinPolicyWindow:boolean;cutoffHours:number;policyGuidance:string;accountingState:string;policyLessonResolution:string;policyFeeCents:number;replacementWindowDays:number|null };
export type OwnerApprovalItem = ProposalApproval | LessonRequestApproval;

export async function loadOwnerApprovals(client:Client,schoolId:string,{teacherId,studentIds,history=false}:{teacherId?:string;studentIds?:string[];history?:boolean}={}){
 let proposalQuery=client.from("lesson_schedule_proposals").select("id,status,teacher_id,student_id,original_starts_at,proposed_starts_at,reason,created_at").eq("school_id",schoolId).eq("proposal_kind","reschedule").order("created_at",{ascending:false});
 proposalQuery=history?proposalQuery.neq("status","pending_owner"):proposalQuery.eq("status","pending_owner");
 if(teacherId)proposalQuery=proposalQuery.eq("teacher_id",teacherId);if(studentIds)proposalQuery=studentIds.length?proposalQuery.in("student_id",studentIds):proposalQuery.in("student_id",["00000000-0000-0000-0000-000000000000"]);
 let requestQuery=client.from("lesson_change_requests").select("id,status,lesson_event_id,request_type,origin_kind,scenario,requested_resolution,requested_at,within_policy_window,cutoff_hours,policy_guidance,accounting_state,policy_version_id").eq("school_id",schoolId).order("requested_at",{ascending:false});
 requestQuery=history?requestQuery.in("status",["approved","declined","withdrawn","superseded"]):requestQuery.in("status",["pending","in_progress"]);
 const [{data:proposalRows,error:proposalError},{data:requestRows,error:requestError}]=await Promise.all([proposalQuery,requestQuery]);
 if(proposalError)throw new Error(`Approvals could not load: ${proposalError.message}`);if(requestError)throw new Error(`Lesson requests could not load: ${requestError.message}`);
 const eventIds=(requestRows??[]).map(row=>row.lesson_event_id);const {data:events,error:eventError}=eventIds.length?await client.from("lesson_events").select("id,student_id,teacher_id,starts_at,ends_at").eq("school_id",schoolId).in("id",eventIds):{data:[],error:null};if(eventError)throw new Error(`Request lessons could not load: ${eventError.message}`);
 const eventMap=new Map((events??[]).map(event=>[event.id,event]));
 const filteredRequests=(requestRows??[]).filter(row=>{const event=eventMap.get(row.lesson_event_id);return event&&(!teacherId||event.teacher_id===teacherId)&&(!studentIds||studentIds.includes(event.student_id));});
 const ids=[...new Set([...(proposalRows??[]).flatMap(row=>[row.teacher_id,row.student_id]),...filteredRequests.flatMap(row=>{const event=eventMap.get(row.lesson_event_id);return event?[event.teacher_id,event.student_id]:[];})])];
 const versionIds=[...new Set(filteredRequests.map(row=>row.policy_version_id))];
 const [{data:people,error:peopleError},{data:policyOutcomes,error:policyError}]=await Promise.all([ids.length?client.from("people").select("id,first_name,last_name,preferred_name").eq("school_id",schoolId).in("id",ids):Promise.resolve({data:[],error:null}),versionIds.length?client.from("cancellation_policy_outcomes").select("id,policy_version_id,scenario,timing_bucket,calendar_action,original_charge_treatment,replacement_kind,expiration_days,adjustment_kind,adjustment_amount_cents").in("policy_version_id",versionIds):Promise.resolve({data:[],error:null})]);
 if(peopleError)throw new Error(`Approval people could not load: ${peopleError.message}`);if(policyError)throw new Error(`Approval policy outcomes could not load: ${policyError.message}`);
 const names=new Map((people??[]).map(person=>[person.id,`${person.preferred_name||person.first_name} ${person.last_name}`]));const outcomeMap=new Map((policyOutcomes??[]).map(outcome=>[`${outcome.policy_version_id}:${outcome.scenario}:${outcome.timing_bucket}`,outcome]));
 const proposals:ProposalApproval[]=(proposalRows??[]).map(row=>({kind:"schedule_proposal",id:row.id,status:row.status,teacherId:row.teacher_id,studentId:row.student_id,teacher:names.get(row.teacher_id)??"Teacher",student:names.get(row.student_id)??"Student",original:row.original_starts_at,proposed:row.proposed_starts_at,reason:row.reason,createdAt:row.created_at}));
 const requests:LessonRequestApproval[]=filteredRequests.flatMap(row=>{const event=eventMap.get(row.lesson_event_id);if(!event)return[];const timing=["teacher_cancellation","school_cancellation","student_no_show"].includes(row.scenario)?"not_applicable":row.within_policy_window?"timely":"late";const outcome=outcomeMap.get(`${row.policy_version_id}:${row.scenario}:${timing}`);if(!outcome)return[];const policyNeedsFinancialReview=["account_credit","reduce_charge","manual_financial_review"].includes(outcome.original_charge_treatment);const policyLessonResolution=policyNeedsFinancialReview||outcome.calendar_action==="manual_review"||outcome.replacement_kind==="manual_review"?"manual_review":outcome.calendar_action==="retain_for_later"?"retain_for_reschedule":outcome.original_charge_treatment==="keep_full_charge"?"count_as_serviced":"waive";return[{kind:"lesson_change_request",id:row.id,status:row.status,teacherId:event.teacher_id,studentId:event.student_id,teacher:names.get(event.teacher_id)??"Teacher",student:names.get(event.student_id)??"Student",lessonAt:event.starts_at,lessonEndsAt:event.ends_at,requestType:row.request_type,originKind:row.origin_kind,scenario:row.scenario,requestedResolution:row.requested_resolution,requestedAt:row.requested_at,withinPolicyWindow:row.within_policy_window,cutoffHours:row.cutoff_hours,policyGuidance:row.policy_guidance,accountingState:row.accounting_state,policyLessonResolution,policyFeeCents:outcome.adjustment_kind==="fee"?outcome.adjustment_amount_cents:0,replacementWindowDays:outcome.expiration_days}];});
 return [...proposals,...requests].sort((a,b)=>new Date(b.kind==="schedule_proposal"?b.createdAt:b.requestedAt).getTime()-new Date(a.kind==="schedule_proposal"?a.createdAt:a.requestedAt).getTime()) satisfies OwnerApprovalItem[];
}
