"use client";
import Link from "next/link";
import { useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { HoldToConfirm } from "@/components/ui/hold-to-confirm";
import { manageNotifications } from "./actions";
type Notice={id:string;title:string;message:string;href:string;kind:string;created_at:string;read_at:string|null;archived_at:string|null};
export function NotificationList({schoolId,notices,archived}:{schoolId:string;notices:Notice[];archived:boolean}){
 const router=useRouter(),[selected,setSelected]=useState<Set<string>>(new Set()),[pending,startTransition]=useTransition(),[message,setMessage]=useState("");
 const ids=[...selected],all=notices.length>0&&selected.size===notices.length;
 function run(action:"read"|"unread"|"restore"){startTransition(async()=>{const result=await manageNotifications(schoolId,ids,action);setMessage(result.message);if(result.ok){setSelected(new Set());router.refresh();}});}
 async function archive(){const result=await manageNotifications(schoolId,ids,"archive");if(result.ok){setSelected(new Set());router.refresh();}return result;}
 return <><div className="flex flex-wrap items-center gap-3 border-y border-line py-4"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={all} onChange={()=>setSelected(all?new Set():new Set(notices.map(n=>n.id)))} /> Select all visible</label>{ids.length?<><button disabled={pending} onClick={()=>run("read")} className="text-sm text-brand">Mark read</button><button disabled={pending} onClick={()=>run("unread")} className="text-sm text-brand">Mark unread</button>{archived?<button disabled={pending} onClick={()=>run("restore")} className="text-sm text-brand">Restore</button>:null}<span className="ml-auto text-xs text-muted">{ids.length} selected</span></>:null}</div>{ids.length&&!archived?<div className="my-5 border-l-2 border-danger pl-5"><p className="text-sm">Archive {ids.length} notification{ids.length===1?"":"s"}? Related records and audit history remain available.</p><div className="mt-3 max-w-xs"><HoldToConfirm action={archive} idleLabel="Hold to archive selected" holdingLabel="Keep holding to archive…" submittingLabel="Archiving…" successLabel="Archived" /></div></div>:null}{message?<p role="status" className="py-3 text-sm text-muted">{message}</p>:null}<div>{notices.length?notices.map(notice=><article key={notice.id} className={`grid grid-cols-[auto_1fr] gap-4 border-b border-line py-5 ${notice.read_at?"text-muted":"text-ink"}`}><input aria-label={`Select ${notice.title}`} type="checkbox" checked={selected.has(notice.id)} onChange={()=>setSelected(current=>{const next=new Set(current);if(next.has(notice.id))next.delete(notice.id);else next.add(notice.id);return next;})}/><div><div className="flex flex-wrap items-start justify-between gap-3"><Link href={notice.href} onClick={()=>{if(!notice.read_at)void manageNotifications(schoolId,[notice.id],"read");}} className="text-sm hover:text-brand">{notice.title}</Link><time className="text-xs text-muted">{new Date(notice.created_at).toLocaleString()}</time></div><p className="mt-2 text-sm leading-6 text-muted">{notice.message}</p><p className="mt-2 text-xs capitalize text-muted">{notice.kind.replaceAll("_"," ")} · {notice.read_at?"Read":"Unread"}</p></div></article>):<p className="py-10 text-sm text-muted">No notifications in this view.</p>}</div></>;
}
