import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { NotificationList } from "./notification-list";
import { ProposalReview } from "./proposal-review";
export const dynamic="force-dynamic";
export default async function NotificationsPage({params,searchParams}:{params:Promise<{schoolId:string}>;searchParams:Promise<{view?:string;proposal?:string}>}){
 const {schoolId}=await params,{view,proposal:proposalId}=await searchParams,archived=view==="archived",supabase=await createClient();
 const {data:school}=await supabase.from("schools").select("name,timezone").eq("id",schoolId).maybeSingle();if(!school)notFound();
 let query=supabase.from("owner_notifications").select("id,title,message,href,kind,created_at,read_at,archived_at").eq("school_id",schoolId).order("created_at",{ascending:false}).limit(100);
 query=archived?query.not("archived_at","is",null):query.is("archived_at",null);const [{data,error},proposalResult]=await Promise.all([query,proposalId&&/^[0-9a-f-]{36}$/i.test(proposalId)?supabase.from("lesson_schedule_proposals").select("id,status,student_id,teacher_id,lesson_event_id,original_starts_at,original_ends_at,proposed_starts_at,proposed_ends_at,reason,proposal_kind").eq("school_id",schoolId).eq("id",proposalId).eq("proposal_kind","reschedule").maybeSingle():Promise.resolve({data:null,error:null})]);if(error)throw new Error(`Notifications could not load: ${error.message}`);
 const proposal=proposalResult.data;let proposalNames=new Map<string,string>();if(proposal){const {data:people}=await supabase.from("people").select("id,first_name,last_name,preferred_name").eq("school_id",schoolId).in("id",[proposal.student_id,proposal.teacher_id]);proposalNames=new Map((people??[]).map(person=>[person.id,`${person.preferred_name||person.first_name} ${person.last_name}`]));}
 const dateTime=new Intl.DateTimeFormat("en-US",{timeZone:school.timezone,weekday:"long",month:"long",day:"numeric",hour:"numeric",minute:"2-digit"});
 return <main className="mx-auto min-h-screen max-w-5xl px-5 py-10 sm:px-8 sm:py-section"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-line pb-7"><div><p className="text-sm text-brand">{school.name}</p><h1 className="mt-3 font-display text-5xl">Notifications</h1><p className="mt-3 text-sm text-muted">A durable record of alerts and requests requiring your attention.</p></div><nav className="flex gap-5 text-sm"><Link href={`/schools/${schoolId}/notifications`} className={!archived?"text-brand":"text-muted"}>Active</Link><Link href={`/schools/${schoolId}/notifications?view=archived`} className={archived?"text-brand":"text-muted"}>Archived</Link></nav></header>{proposal?<div className="mt-8"><ProposalReview schoolId={schoolId} proposalId={proposal.id} status={proposal.status} student={proposalNames.get(proposal.student_id)??"Student"} teacher={proposalNames.get(proposal.teacher_id)??"Teacher"} original={proposal.original_starts_at?dateTime.format(new Date(proposal.original_starts_at)):"Original time unavailable"} proposed={dateTime.format(new Date(proposal.proposed_starts_at))} reason={proposal.reason}/></div>:proposalId?<p role="alert" className="mt-8 border border-danger/40 p-4 text-sm text-danger">That proposal is unavailable or does not belong to this school.</p>:null}<div className="mt-8"><NotificationList schoolId={schoolId} notices={data??[]} archived={archived}/></div></main>;
}
